<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages': ['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Numero Noleggi');
        data.addRows([
            ['Gennaio', <?= $this->Prenotazioni[1] ?>],
            ['Febbraio', <?= $this->Prenotazioni[2] ?>],
            ['Marzo', <?= $this->Prenotazioni[3] ?>],
            ['Aprile', <?= $this->Prenotazioni[4] ?>],
            ['Maggio', <?= $this->Prenotazioni[5] ?>],
            ['Giugno', <?= $this->Prenotazioni[6] ?>],
            ['Luglio', <?= $this->Prenotazioni[7] ?>],
            ['Agosto', <?= $this->Prenotazioni[8] ?>],
            ['Settembre', <?= $this->Prenotazioni[9] ?>],
            ['Ottobre', <?= $this->Prenotazioni[10] ?>],
            ['Novembre', <?= $this->Prenotazioni[11] ?>],
            ['Dicembre', <?= $this->Prenotazioni[12] ?>]
        ]);

        // Set chart options
        var options = {'title': 'Noleggio Mensile',
            'width': 600,
            'height': 400};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>
<script>
    function toggle_visibility(id) {
        var e = document.getElementById(id);
        e.style.display = ((e.style.display !== 'none') ? 'none' : 'inline-block');
    }
</script>
</head>

<body>
    <!--Statistica (auto noleggiate nel mese) solo marca, modello, targa e del cliente che le ha noleggiate-->
    <?php
    $mesi = array(
        1 => 'Gennaio',
        2 => 'Febbraio',
        3 => 'Marzo',
        4 => 'Aprile',
        5 => 'Maggio',
        6 => 'Giugno',
        7 => 'Luglio',
        8 => 'Agosto',
        9 => 'Settembre',
        10 => 'Ottobre',
        11 => 'Novembre',
        12 => 'Dicembre');
    ?>
<center><div id="chart_div"></div></center>
<center><div id="statistica">
        <table class="statistica">
            <thead>
            <td>MESE</td>
            <td>Numero Noleggi</td>
            </thead>
            <tbody>
                <?php for ($i = 1; $i < 13; $i++): ?>
                    <tr>
                        <td><?= $mesi[$i] ?></td>
                        <td><?= $this->Prenotazioni[$i] ?></td>
                    </tr>
                <?php endfor; ?>

            </tbody>
        </table>

    </div>
</center>
</body>
</html>