<div style="width:100%; opacity:0.7; background-color: white;">
    <center><h1>Area Staff</h1></center>
    <center><h2>Seleziona la funzione da attivare</h2></center>
    <center><h2>Benvenuto <?= $this->authInfo('Nome') . ' ' . $this->authInfo('Cognome') ?> </h2></center>
</div>
<?php
$url_auto = $this->url(array('controller' => 'staff', 'action' => 'showcars'), 'default', true);
$url_auto_add = $this->url(array('controller' => 'staff', 'action' => 'newauto'), 'default', true);
$url_profile = $this->url(array('controller' => 'staff', 'action' => 'editprofile', 'Id' => $this->authInfo('IDUtente')), 'default', true);
$url_statistica = $this->url(array('controller' => 'staff', 'action' => 'statistica'), 'default', true);
?>
<center
    <div>
        <div class="pannello_componente" ><img class="loghi" src="<?= $this->baseUrl('images/logo_noleggio.png') ?>"><br>

            <a href="<?= $url_auto ?>">Gestione AUTO</a><br>
            <a href="<?= $url_auto_add ?>">Inserisci AUTO</a>
        </div>

        <div 

            class="pannello_componente" ><img class="loghi" src="<?= $this->baseUrl('images/logo_admin.png') ?>"><br>
            <a href="<?= $url_profile ?>">MODIFICA PROFILO</a><br>

        </div>
        <div class="pannello_componente" ><img class="loghi" src="<?= $this->baseUrl('images/logo_statistica.png') ?>"><br> <a href="<?= $url_statistica ?>">STATISTICA</a><br></div>




    </div>
</center>
