<?php if ($this->pageCount > 1): ?>
    <div class="paginazione_elementi">
        <center><?php echo 'Auto visualizzate da ' . $this->firstItemNumber . ' a ' . $this->lastItemNumber; ?> di <?= $this->totalItemCount; ?></center>
    </div>

    <div class="paginazione">
        <center>
            <?php if (isset($this->previous)): ?>
                <a class="page" href="<?= $this->url(array('controller' => 'public', 'action' => 'catalogo', 'page' => $this->first)); ?>">Inizio</a>
            <?php else: ?>
                <a class="page">Inzio</a>
            <?php endif; ?>

            <?php if (isset($this->previous)): ?>
                <a class="page" href="<?= $this->url(array('controller' => 'public', 'action' => 'catalogo', 'page' => $this->previous)); ?>">&lt; Precedente</a>
            <?php else: ?>
                <a class="page"> &lt; Precedente</a>
            <?php endif; ?>

            <?php if (isset($this->next)): ?>
                <a class="page"href="<?= $this->url(array('controller' => 'public', 'action' => 'catalogo', 'page' => $this->next)); ?>">Successivo &gt;</a>
            <?php else: ?>
                <a class="page">Successivo &gt;</a>
            <?php endif; ?>

            <?php if (isset($this->next)): ?>
                <a class="page" href="<?= $this->url(array('controller' => 'public', 'action' => 'catalogo', 'page' => $this->last)); ?>">Fine</a>
            <?php else: ?>
                <a class="page">Fine</a>
            <?php endif; ?>
        </center>
    </div>

<?php endif; ?>