<div>
<?php $url_ricerca = $this->url(array('controller' => 'public', 'action' => 'catalogo'),'default',true ); ?>
	<div class="video_noleggio"> 
		<div class="form_noleggio">
                    <img src="<?=$this->baseUrl('images/logo_sito.png')?>" width="500px" height="500px" >
                </div>
	</div>
	<div class="meteopark">
			<div class="meteo">
				<iframe src="https://www.meteo.it/mymeteo/widget/public/it/widget_72h.shtml?i=42002&mt=1&r=11&f=Arial" width="100%" height="351px" frameborder="0" scrolling="no"></iframe></div>
			<div class="park">
				<img src="<?=$this->baseUrl('images/park.jpg')?>" alt="parcheggio" class="park_img">
			</div>
	</div>
</div>
