<div class="regolamento_testo">
    <br>
    <center>
        <div class="who_testo">
            <h1 style="color:white;">Regolamento</h1><br>
            <h3>A chi è rivolto il nostro servizio</h3>
            Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. 
            In nulla tortor, elementum vel, tempor at, varius non, purus. <br>Mauris vitae nisl nec metus placerat consectetuer. 
            Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, 
            ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. 
            Phasellus pellentesque. <br> Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.

            <h3>Come si accede al servizio</h3>

            Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. 
            In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. 
            Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, 
            ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante.<br> In id eros. Suspendisse lacus turpis, cursus egestas at sem. 
            Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.

            <h3>La nostra policy </h3>
            Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. 
            In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. 
            Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, 
            ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. 
            Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.
        </div>
    </center>
    <br>
</div>
