<div class="static">
	<div class="pannello_contact">
		<div class="mapouter">
				<div class="gmap_canvas">
						<iframe class="mappa_google"  id="gmap_canvas" src="https://maps.google.com/maps?q=ancona%2C%20via%20brecce%20bianche%2C30&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
						</iframe>
				</div>
		</div>
		<div class="contatti">
				<p><img class="social" src="<?=$this->baseUrl('images/logo_mappa.png')?>" /> Via Brecce Bianche, 30 <br>Ancona, 61022 <br> Italy, Marche </p>
				<p><img class="social" src="<?=$this->baseUrl('images/logo_telefono.png')?>" /><a href="tel:+390123456789">Chiama +39.0123.456789!</a></p>
				
			<!-- Icone Social Network - Inizio -->
			<table class="social"> 
				<tr class="social"> 
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-RSUcXlDOlJw/WS0ciCGtDoI/AAAAAAAA80M/yTi-TKJqfOEpMigNI9a01KUEsEFDZjZmQCHM/s720/facebook.png'/></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-jwcz1pI-t0w/WS0ciAdGzYI/AAAAAAAA80M/-BJ3NZomRRoMs2VJzAT7HhCGbNcyItIUwCHM/s720/twitter.png' /></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-6xyavm_zn8E/WS0ciDwkHoI/AAAAAAAA80M/X1zGroa5xHEQCE3cE5R7tZgqjgzHik2bwCHM/s720/googleplus.png'/></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-eLpnLWToHiY/WS0knHpljmI/AAAAAAAA80w/PyiMi2x04Ts7NhOPwzkX3cgEasXIwoxXgCHM/s720/linkedin.png'/></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-0kgphg6b_Ro/WS0ciDWH-MI/AAAAAAAA80M/9sExNcNsrGEx97R6e3TXapjT31wk_DClACHM/s720/telegram.png'/></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-BmtlU-Oppfc/WS0ciHvsMhI/AAAAAAAA80M/C7SBFFe-0rEk2yqZLTfpRi4toXP_iuCywCHM/s720/whatsapp.png'/></td>
					<td class="social"><img class="social" src='https://lh3.googleusercontent.com/-JM8vxgiM02o/WS0tDuiYlOI/AAAAAAAA81g/HewyYuonFbgLjVroe3h8UTmnE_g32mEKACHM/s720/gmail.png'/></td>
				</tr>
			</table>
			<!-- Icone Social Network - Fine -->
		</div>
	</div>
</div>
